#!/bin/bash
 
set -e -x

# ensure gosub is installed (this will recompile it only if necessary)
go get github.com/vito/gosub
go install github.com/vito/gosub

{
  gosub list \
    -app github.com/crhino/perf-server/cmd/... \

  # separate these so gosub doesn't asplode
  gosub list -test github.com/crhino/perf-server/...
} > /tmp/packages

cat /tmp/packages | xargs gosub sync
